<a href="https://colab.research.google.com/github/agbizbuz/learning-ai-ds-ml/blob/main/simplilearn_ml_python/tensorflow_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
minst = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = minst.load_data()
x_train, x_test = x_train/255, x_test/255

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [5]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(128, activation='relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.31699044, -0.07798426,  0.5601449 ,  0.1634298 ,  0.28063062,
        -0.15033045,  0.1742708 , -0.28945455, -0.15458834,  0.20038663]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.12013713, 0.08093603, 0.15320675, 0.10303546, 0.11584742,
        0.07528742, 0.10415856, 0.06550909, 0.07496753, 0.10691456]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.5864422)

In [9]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9148 - loss: 0.2918
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9589 - loss: 0.1413
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9673 - loss: 0.1064
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9737 - loss: 0.0852
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9770 - loss: 0.0741


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9786 - loss: 0.0711


[0.07112547010183334, 0.978600025177002]

In [11]:
proba_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])
proba_model(x_test[:3])

<tf.Tensor: shape=(3, 10), dtype=float32, numpy=
array([[1.6075807e-06, 3.4680432e-09, 4.2506904e-06, 4.1210029e-04,
        3.7813322e-11, 1.3992740e-06, 3.3320449e-12, 9.9957663e-01,
        1.0857778e-07, 3.9881493e-06],
       [2.9172026e-10, 1.5555123e-04, 9.9984086e-01, 3.5892233e-06,
        3.3842395e-14, 2.6603184e-08, 7.7562273e-10, 1.8464154e-11,
        5.8788725e-08, 1.5907990e-11],
       [2.4815247e-07, 9.9789304e-01, 1.9986734e-05, 3.6684439e-06,
        2.3682817e-04, 2.5243403e-06, 4.2804917e-05, 1.5844218e-03,
        2.1601014e-04, 4.8188127e-07]], dtype=float32)>